[package]
name = "gdkit"
description = "Godot development utility belt. Thin CLI over gdproject and gdview."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "gdkit"
path = "src/main.rs"

[dependencies]
gdview.workspace = true
gdproject.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
anstream.workspace = true

[lints]
workspace = true
